#################################################
#  Company    : Stevens 
#  Project    : CS 513 B- Prediction of Vehicle Collision Severity using NYPD Data 2017 
#  Purpose    : Final Project
#  Topic      : Naive Bayes
#  Date       : 12/7/2018


rm(list=ls())
#################################################

#######NYPD COLLISION PREDICTION#####

#### Reading the CSV File ####
NYPD_NAIVE <- read.csv("C:/Users/HP/Desktop/513 Project/NYPD2017.csv")

#### Removing the rows with NA in Location, Latitude, Longitude & Zip Code ####
NYPD_NAIVEBAYES<-na.omit(NYPD_NAIVE)

#### Adding rows with killed or injured to find the total Killed and Injured ####
NYPD_NAIVEBAYES$KILLED <- NYPD_NAIVEBAYES$NUMBER.OF.PERSONS.KILLED + NYPD_NAIVEBAYES$NUMBER.OF.PEDESTRIANS.KILLED + NYPD_NAIVEBAYES$NUMBER.OF.CYCLIST.KILLED + NYPD_NAIVEBAYES$NUMBER.OF.MOTORIST.KILLED
NYPD_NAIVEBAYES$INJURED <- NYPD_NAIVEBAYES$NUMBER.OF.PERSONS.INJURED + NYPD_NAIVEBAYES$NUMBER.OF.PEDESTRIANS.INJURED + NYPD_NAIVEBAYES$NUMBER.OF.CYCLIST.INJURED + NYPD_NAIVEBAYES$NUMBER.OF.MOTORIST.INJURED

#### As we are predicting injured or not, we are changing the total injured to binary ####
NYPD_NAIVEBAYES$INJURED <- replace(NYPD_NAIVEBAYES$INJURED, NYPD_NAIVEBAYES$INJURED > 0, 1)
NYPD_NAIVEBAYES$INJURED <- replace(NYPD_NAIVEBAYES$INJURED, NYPD_NAIVEBAYES$INJURED == 0, 0)

#### Taking month from date for categorization ####
NYPD_NAIVEBAYES$DATE <- as.Date(NYPD_NAIVEBAYES$DATE,"%d-%m-%Y")
NYPD_NAIVEBAYES$MONTH <- strftime(NYPD_NAIVEBAYES$DATE,"%m")

#### categorizing the time into 6 divisions ####
NYPD_NAIVEBAYES$TIME <- gsub(":.*","",NYPD_NAIVEBAYES$TIME)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME >= 4 & NYPD_NAIVEBAYES$TIME < 8, 2)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME >= 8 & NYPD_NAIVEBAYES$TIME < 12, 3)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME >= 12 & NYPD_NAIVEBAYES$TIME < 16, 4)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME >= 16 & NYPD_NAIVEBAYES$TIME < 20, 5)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME >= 20 & NYPD_NAIVEBAYES$TIME < 24, 6)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME == 8, 3)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME == 9, 3)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME == 10, 3)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME == 11, 3)
NYPD_NAIVEBAYES$TIME <- replace(NYPD_NAIVEBAYES$TIME, NYPD_NAIVEBAYES$TIME >= 0 & NYPD_NAIVEBAYES$TIME < 4, 1)

#### Replacing the "Blanks" with "unknown" for Vehicle Type Code ####
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.2 <- sub("^$","UNKNOWN",NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.2)
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.1 <- sub("^$","UNKNOWN",NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.1)
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.3 <- sub("^$","UNKNOWN",NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.3)
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.4 <- sub("^$","UNKNOWN",NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.4)
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.5 <- sub("^$","UNKNOWN",NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.5)

#### Replacing the "Blanks" with "Unspecified" for CONTRIBUTING FACTORS ####
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.1 <- sub("^$","Unspecified",NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.1)
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.2 <- sub("^$","Unspecified",NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.2)
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.3 <- sub("^$","Unspecified",NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.3)
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.4 <- sub("^$","Unspecified",NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.4)
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.5 <- sub("^$","Unspecified",NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.5)

#### Categorizing the DataSet into Numericals ####
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.2 <- as.integer(as.factor(NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.2))
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.1 <- as.integer(as.factor(NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.1))
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.3 <- as.integer(as.factor(NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.3))
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.4 <- as.integer(as.factor(NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.4))
NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.5 <- as.integer(as.factor(NYPD_NAIVEBAYES$VEHICLE.TYPE.CODE.5))
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.1 <- as.integer(as.factor(NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.1))
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.2 <- as.integer(as.factor(NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.2))
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.3 <- as.integer(as.factor(NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.3))
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.4 <- as.integer(as.factor(NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.4))
NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.5 <- as.integer(as.factor(NYPD_NAIVEBAYES$CONTRIBUTING.FACTOR.VEHICLE.5))
NYPD_NAIVEBAYES$LOCATION <- as.integer(NYPD_NAIVEBAYES$LOCATION)
NYPD_NAIVEBAYES$ZIP.CODE <- as.integer(NYPD_NAIVEBAYES$ZIP.CODE)
NYPD_NAIVEBAYES$ON.STREET.NAME <- as.integer(NYPD_NAIVEBAYES$ON.STREET.NAME)
NYPD_NAIVEBAYES$CROSS.STREET.NAME <- as.integer(NYPD_NAIVEBAYES$CROSS.STREET.NAME)
NYPD_NAIVEBAYES$OFF.STREET.NAME <- as.integer(NYPD_NAIVEBAYES$OFF.STREET.NAME)
NYPD_NAIVEBAYES$BOROUGH <- as.integer(NYPD_NAIVEBAYES$BOROUGH)
NYPD_NAIVEBAYES$MONTH <- as.integer(NYPD_NAIVEBAYES$MONTH)
NYPD_NAIVEBAYES$INJURED <- as.integer(NYPD_NAIVEBAYES$INJURED)
NYPD_NAIVEBAYES$KILLED <- as.integer(NYPD_NAIVEBAYES$KILLED)
NYPD_NAIVEBAYES$TIME <- as.integer(NYPD_NAIVEBAYES$TIME)
NYPD_NAIVEBAYES$LATITUDE <- as.integer(NYPD_NAIVEBAYES$LATITUDE)
NYPD_NAIVEBAYES$LONGITUDE <- as.integer(NYPD_NAIVEBAYES$LONGITUDE)

#### Taking every 5th row into the test dataset, and remaining into the training dataset ####
index <- seq (1,nrow(NYPD_NAIVEBAYES),by=5)
test<-NYPD_NAIVEBAYES[index,]
training<-NYPD_NAIVEBAYES[-index,]
str(training)

#### Taking all the features except the unique key, date and seperate counts of killed and injured ####
training <- training[,c(-1,-11,-12,-13,-14,-15,-16,-17,-18,-24)]
test <- test[,c(-1,-11,-12,-13,-14,-15,-16,-17,-18,-24)]
library(class)
library(e1071)

####  Naive Bayes ####
Naivebayes_1<-naiveBayes(factor(INJURED)~.,training)

plot(Naivebayes_1)
Naivebayes_1

#### Prediction ####
Naiveprediction<-predict(Naivebayes_1,test[,-21])

#### Error Rate ####
Naive_Wrong<-(test$INJURED!=Naiveprediction)
Naive_Wrong
rate_CART<-sum(Naive_Wrong)/length(Naive_Wrong)
rate_CART
